[project]
name = "TeNe"
version = "0.1.0"
description = "A python library for tensor network simulation of quantum many-body systems."
readme = "README.md"
authors = [
    { name = "alsoblank", email = "luke.causer@outlook.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
]

[project.scripts]
tene = "tene:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]

[tool.ruff]
line-length=92
target-version = "py313"
force-exclude = true

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # Pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "UP",     # pyupgrade
    "SIM",    # flake8-simplify
    "C4",     # flake8-comprehensions
    "RUF",    # Ruff-specific rules
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[tool.pytest.ini_options]
testpaths = ["tests/unit", "src"]
addopts = "--doctest-modules"
